# Generated by Django 2.2 on 2020-01-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_auto_20200121_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='incidents',
            new_name='example_inc',
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
