# Generated by Django 2.2 on 2020-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0003_auto_20200121_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='uploader',
            field=models.TextField(default='NA'),
        ),
    ]
