# Generated by Django 2.2 on 2020-02-05 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_issue_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sys_creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
