# Generated by Django 2.2 on 2020-02-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP1', '0005_issue_sys_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='uploader',
        ),
        migrations.AddField(
            model_name='issue',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
